yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Home page
    path('', views.index, name='index_page'),
    # Groups
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
]

yatube/yatube/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


# Groups model
class Group(models.Model):
    title = models.CharField(
        max_length=200,
    )
    slug = models.SlugField(
        unique=True,
        max_length=200,
    )
    description = models.TextField()

    def __str__(self):
        return self.title


# Post model
class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True
    )
    ordering = ['-pub_date']

yatube/posts/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

# Posts on page quantity constant
POSTS_QUANTITY: int = 10


# Home page
def index(request):
    # Get posts order by pub
    posts: dict = Post.objects.select_related('group').all()[:POSTS_QUANTITY]
    context: dict = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


# Groups page
def group_posts(request, slug):
    # get_object_or_404
    group: Any = get_object_or_404(Group, slug=slug)
    # Get posts, filter by group, order by pub
    posts: dict = group.posts.all()[:POSTS_QUANTITY]
    context: dict = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Charset -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicons -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
        {% block page_title %}
            Последние обновления на сайте
        {% endblock %}
    </title>
  </head>
  <body>
    <!-- Header -->
    {% include 'includes/header.html' %}
    <!-- Content -->
    <main>
        <div class="container py-5">
        {% block content %}
            {% block title %}
                <h1>Home</h1>
            {% endblock %}
            No posts
        {% endblock %}
        </div>
    </main>
    <!-- Footer -->
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}

<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index_page' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
    </div>
    </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block page_title %}
    Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}
    {% block title %}
        <h1>Записи сообщества {{ group.title }}</h1>
    {% endblock %}
    <p>
        {{ group.description }}
    </p>
    {% for post in posts %}
        {% include 'posts/includes/posts.html' %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}

yatube/templates/posts/includes/posts.html
<article>
    <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group.slug %}
    <a href="{% url 'posts:group_posts' slug=post.group.slug %}">все записи группы</a>
    {% endif %}
</article>

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block page_title %}
    Последние обновления на сайте
{% endblock %}

{% block content %}
    {% block title %}
        <h1>Последние обновления на сайте</h1>
    {% endblock %}
    {% for post in posts %}
        {% include 'posts/includes/posts.html' %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}